branch-defaults:
  master:
    environment: django-env
environment-defaults:
  django-env:
    branch: null
    repository: null
global:
  application_name: cau-lion-server
  default_ec2_keyname: aws-eb
  default_platform: Python 3.7 running on 64bit Amazon Linux 2
  default_region: ap-northeast-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  sc: git
  workspace_type: Application
